const EventBuilder = require('../src/builders/eventBuilder')
const Conference = require('../src/builders/conference')
const Person = require('../src/builders/person')
const Timespan = require('../src/utilities/enums/timespan')
const FeatureType = require('../src/utilities/enums/feature')

var eb = new EventBuilder()
eb.setDescription('Here is a test description')
    .addOrganizer(new Person('hivie7510@gmail.com', 'Heath Ivie'))
    .addOrganizers([new Person('hivie7510@gmail.com', 'Heath Ivie')])
    .addAttendee(new Person('hivie7510@gmail.com', 'Heath Ivie'))
    .addAttendees([new Person('hivie7510@gmail.com', 'Heath Ivie')])
    .setStart(new Date())
    .setEnd(new Date())
    .setName('Make sure you meet me here')
    .setUrl('http://www.google.com')
    .addCategory('Meeting')
    .addCategories('my meeting, you meeting')
    .setRefreshInterval(Timespan.WEEK, 10)
    .setSourceUrl('http://www.mycalendar.com/test.ics')
    .setColor('red')
    .setImageUrl('http://www.myimage.com/thumbnail.jpg')
    .addConferenceInfo(new Conference(FeatureType.AUDIO, 'Moderator dial-in:tel:+1-412-555-0123,,,654321'))
    .addConferenceInfo(
        new Conference([FeatureType.AUDIO, FeatureType.MODERATOR], 'Moderator dial-in:tel:+1-412-555-0123,,,654321')
    )
console.log(eb.build())
