const CalendarBuilder = require('../src/builders/calendarBuilder')
const EventBuilder = require('../src/builders/eventBuilder')
const Conference = require('../src/builders/conference')
const Attendee = require('../src/builders/attendee')
const Organizer = require('../src/builders/organizer')
const Timespan = require('../src/utilities/enums/timespan')
const FeatureType = require('../src/utilities/enums/feature')

var eb = new EventBuilder()
eb.setDescription('Here is a test description')
    .addOrganizer(new Organizer('hivie7510@gmail.com', 'Heath Ivie'))
    .addOrganizers([new Organizer('hivie75101@gmail.com', 'Heath1 Ivie')])
    .addAttendee(new Attendee('hivie7510@gmail.com', 'Heath Ivie'))
    .addAttendees([new Attendee('hivie7510@gmail.com', 'Heath Ivie')])
    .setStart(new Date())
    .setEnd(new Date())
    .setSummary('Make sure you meet me here')
    .setDescription("We're having a pool party")
    .setUrl('http://www.google.com')
    .addCategory('Meeting')
    .addCategories('my meeting, you meeting')
    .setRefreshInterval(Timespan.WEEK, 10)
    .setSourceUrl('http://www.mycalendar.com/test.ics')
    .setColor('red')
    .setImageUrl('http://www.myimage.com/thumbnail.jpg')
    .addConferenceInfo(new Conference(FeatureType.AUDIO, 'Moderator dial-in:tel:+1-412-555-0123,,,654321'))
    .addConferenceInfo(
        new Conference([FeatureType.AUDIO, FeatureType.MODERATOR], 'Moderator dial-in:tel:+1-412-555-0123,,,654321')
    )

var c = new CalendarBuilder()
c.addEvent(eb)
console.log(c.build())
